name: d_locker
description: A new Flutter project.
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=2.19.2 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  coinbase_wallet_sdk: ^1.0.6
  walletconnect_dart: ^0.0.11
  razorpay_flutter: ^1.3.4
  flutter_dotenv: ^5.0.2
  flutter_riverpod: ^1.0.3
  shared_preferences: ^2.0.11
  web3dart: ^2.0.0
  web_socket_channel: ^2.1.0
  
dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  firebase_auth: ^4.2.10
  firebase_core: ^2.7.1
  cloud_firestore: ^4.4.4
  firebase_storage: ^11.0.16
  provider: ^6.0.5
  google_sign_in: ^5.4.4
  liquid_swipe: ^3.0.0
  smooth_page_indicator: ^1.0.1
  get: ^4.6.5
  google_fonts: ^4.0.3
  font_awesome_flutter: ^10.4.0
  flutter_zoom_drawer: ^2.1.1
  curved_navigation_bar: ^1.0.3
  awesome_card: ^1.1.6
  hexcolor: ^3.0.1
  flutter_svg: ^2.0.3
  file_picker: ^5.2.6
  mime: ^1.0.4
  path_provider: ^2.0.14
  uuid: ^3.0.7
  flutter_image_compress: ^1.1.3
#  flutter_ffmpeg: ^0.4.2
  video_compress: ^3.1.2
  ffmpeg: ^0.0.1
  url_launcher: ^6.1.10
  audioplayers: ^0.20.0
  chewie: ^1.4.0
  video_player: ^2.6.0
  flutter_downloader: ^1.10.2
  permission_handler: ^10.2.0
  flutter_launcher_icons: ^0.12.0
  http: ^0.13.5
  dio: ^5.1.0
  flutter_pdfview: ^1.2.9
  flutter_credit_card: ^3.0.6


flutter_icons:
  image_path: "assets/app-logo1.png"
  android: true
  ios: true


# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/
    - assets/contracts_abis/Investment.json
    - .env

  fonts:
    - family: Montserrat
      fonts:
        - asset: assets/fonts/Montserrat-Regular.ttf
        - asset: assets/fonts/Montserrat-Bold.ttf
        - asset: assets/fonts/Montserrat-Light.ttf
          weight: 700  
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
